# Site settings
title: DevOps/SRE portfolio 
description: This is my simple portfolio 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sergio Lattke
user_description: DevOps junior fond of technologies, I have knowledge in Python, JavaScript, puppet and Linux. I also have basic knowledge in AWS and Oracle cloud. I am a person who adapts easily, and I have no problem working in a team, I love to learn new things.
user_title: DevOps Engineer jr
email: sergiolattk@outlook.com
github_username:  bacuchito


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
