# Site settings
title: DevOps/SRE portfolio 
description: This is my simple portfolio 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sergio Lattke
user_description: 
user_title: DevOps Engineer jr
email: sergiolattk@outlook.com
twitter_username: lorem_ipsum
github_username:  bacuchito
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
